### ISSUE TITLE
230404 회고

### ISSUE THREAD

**Issue by tkd8973** [BigData23th/DeepLearning#50]
K : 복습을 잘 하고 GPT사용을 용이하게 하자 딥러닝 어렵따
P : GPT가 가끔 고장이난다, 내 질문 실력이 부족한 것 같으니 더 연습하자
T : 질문연습과 GAN을 사용하면 뭔가 재밌는 작품을 만들 수 있을 것 같으니 해보자. ex) 사람 얼굴 -> 침팬치 원숭이..

[FER2013데이터](https://sharegpt.com/c/ZVBs82c)

**Comment by qus0in** [comment]
👍
